apiVersion: v1
kind: Pod
metadata:
  labels:
    name: secret-test
  name: secret-test
spec:
  volumes:
  - name: secrets
    secret:
      secretName: mysecret
  containers:
  - image: nginx:1.20
    name: my-hard
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true